name: Sync from Owner

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: oci-syncer-c2fd2fca-1a0a-4d31-aefb-5650a99f6c3f
          fetch-depth: 0

      - name: Run sync script
        env:
          UPSTREAM_OWNER: ${{ vars.OC_UPSTREAM_OWNER }}
          UPSTREAM_REPO: ${{ vars.OC_UPSTREAM_REPO }}
          DEST_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.OCI_PUB_SYNC_PAT }}

          PRUNE_DELETIONS: "true"
          SKIP_WORKFLOW_CHANGES: "true"
          EXCLUDE_BRANCH: oci-syncer-c2fd2fca-1a0a-4d31-aefb-5650a99f6c3f
        run: |
          chmod +x scripts/sync-from-owner.sh
          ./scripts/sync-from-owner.sh
